import { Product, Category, Order } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Women's Collection",
    slug: "women",
    description: "Architectural cuts and flowing silk drapery for the discerning modern woman.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&q=80",
    itemCount: 42,
  },
  {
    id: "cat-2",
    name: "Men's Tailoring",
    slug: "men",
    description: "Relaxed silhouettes, structured overshirts, and artisanal Japanese selvedge.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900&q=80",
    itemCount: 38,
  },
  {
    id: "cat-3",
    name: "Evening & Occasion",
    slug: "evening",
    description: "Sculptural gowns, metallic accents, and midnight velvet luxury.",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&q=80",
    itemCount: 19,
  },
  {
    id: "cat-4",
    name: "Leather & Accents",
    slug: "accessories",
    description: "Handcrafted Tuscan leather bags, minimalist belts, and statement eyewear.",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=900&q=80",
    itemCount: 24,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Sculpted Hourglass Wool Blazer",
    slug: "sculpted-hourglass-wool-blazer",
    subtitle: "SS'26 Runway Capsule",
    price: 8490,
    regularPrice: 11990,
    onSale: true,
    saleBadge: "SAVE 29%",
    description: "Meticulously cut from double-faced Italian virgin wool, this hourglass blazer redefines contemporary power dressing. Designed with structured pagoda shoulders, a cinched waistline, and handcrafted horn buttons.",
    shortDescription: "Italian double-faced virgin wool with structured pagoda shoulders.",
    category: {
      name: "Women",
      slug: "women",
    },
    images: [
      {
        id: "img-1-1",
        sourceUrl: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1000&q=85",
        altText: "Front view of Sculpted Hourglass Wool Blazer",
      },
      {
        id: "img-1-2",
        sourceUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1000&q=85",
        altText: "Editorial side angle of Sculpted Blazer",
      },
      {
        id: "img-1-3",
        sourceUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=85",
        altText: "Fabric and button close-up",
      },
    ],
    colorOptions: [
      { name: "Obsidian Noir", hex: "#18181b" },
      { name: "Sandstone Camel", hex: "#c2a688" },
      { name: "Alabaster Cream", hex: "#f4f1ea" },
    ],
    sizeOptions: ["XS", "S", "M", "L", "XL"],
    sku: "ZEL-BLZ-001",
    stockQuantity: 7,
    inStock: true,
    rating: 4.9,
    reviewCount: 38,
    fabricCare: "100% Italian Virgin Wool. Lining: 100% Cupro. Specialist dry clean only. Cool iron under pressing cloth.",
    shippingInfo: "Complimentary worldwide express shipping. Dispatched in signature Zelevation garment box within 24 hours.",
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "prod-2",
    name: "Oversized Raw Silk Camp Shirt",
    slug: "oversized-raw-silk-camp-shirt",
    subtitle: "Unisex Atelier Series",
    price: 4990,
    regularPrice: 5990,
    onSale: true,
    saleBadge: "LIMITED DROP",
    description: "Crafted from handloomed raw mulberry silk featuring an organic slub texture. Features an easy convertible camp collar, mother-of-pearl buttons, and side vents for an effortless drape.",
    shortDescription: "Organic slub silk shirt with Cuban camp collar and shell buttons.",
    category: {
      name: "Men",
      slug: "men",
    },
    images: [
      {
        id: "img-2-1",
        sourceUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1000&q=85",
        altText: "Model wearing Oversized Raw Silk Camp Shirt",
      },
      {
        id: "img-2-2",
        sourceUrl: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1000&q=85",
        altText: "Front relaxed view",
      },
    ],
    colorOptions: [
      { name: "Raw Ecru", hex: "#eae6df" },
      { name: "Olive Moss", hex: "#4b5320" },
      { name: "Midnight Navy", hex: "#1c2833" },
    ],
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    sku: "ZEL-SHR-004",
    stockQuantity: 12,
    inStock: true,
    rating: 4.8,
    reviewCount: 22,
    fabricCare: "100% Handspun Mulberry Raw Silk. Hand wash cold with mild silk detergent or eco-dry clean.",
    shippingInfo: "Express courier with tracking delivered in 2-4 business days.",
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "prod-3",
    name: "Pleated Wide-Leg Palazzo Trousers",
    slug: "pleated-wide-leg-palazzo-trousers",
    subtitle: "High-Rise Minimalist Cut",
    price: 5200,
    regularPrice: 6500,
    onSale: true,
    saleBadge: "BESTSELLER",
    description: "A dramatic wide-leg silhouette cut from high-density Japanese Tencel twill. Designed with deep front inverted pleats, slanted pockets, and an internal hook-and-bar closure for a seamless waist.",
    shortDescription: "Japanese fluid twill with deep front knife pleats.",
    category: {
      name: "Women",
      slug: "women",
    },
    images: [
      {
        id: "img-3-1",
        sourceUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1000&q=85",
        altText: "Pleated Wide-Leg Trousers full length",
      },
      {
        id: "img-3-2",
        sourceUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=85",
        altText: "Waist detail and pleat folds",
      },
    ],
    colorOptions: [
      { name: "Charcoal Slate", hex: "#2f3542" },
      { name: "Desert Chalk", hex: "#e4ded4" },
    ],
    sizeOptions: ["XS", "S", "M", "L"],
    sku: "ZEL-TRS-009",
    stockQuantity: 4,
    inStock: true,
    rating: 5.0,
    reviewCount: 47,
    fabricCare: "70% Tencel Lyocell, 30% Linen. Gentle machine wash inside out in mesh bag.",
    shippingInfo: "Fast 48-hour dispatch with tamper-proof seal.",
    isFeatured: true,
  },
  {
    id: "prod-4",
    name: "Cashmere Heavyweight Turtleneck",
    slug: "cashmere-heavyweight-turtleneck",
    subtitle: "7-Gauge Mongolian Cashmere",
    price: 9900,
    regularPrice: 12900,
    onSale: true,
    saleBadge: "SAVE 23%",
    description: "Spun from Grade-A certified Mongolian cashmere fibers. Features a thick ribbed roll neck, dropped shoulders, and chunky ribbed hem cuffs for supreme thermal comfort and relaxed elegance.",
    shortDescription: "Grade-A certified 7-gauge pure Mongolian cashmere.",
    category: {
      name: "Women",
      slug: "women",
    },
    images: [
      {
        id: "img-4-1",
        sourceUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1000&q=85",
        altText: "Cashmere Turtleneck model shot",
      },
      {
        id: "img-4-2",
        sourceUrl: "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=1000&q=85",
        altText: "Ribbed knit texture close-up",
      },
    ],
    colorOptions: [
      { name: "Oatmeal Heather", hex: "#d9d2c9" },
      { name: "Espresso", hex: "#3e2723" },
      { name: "Pure Black", hex: "#111111" },
    ],
    sizeOptions: ["XS", "S", "M", "L"],
    sku: "ZEL-KNT-012",
    stockQuantity: 3,
    inStock: true,
    rating: 4.9,
    reviewCount: 16,
    fabricCare: "100% Sustainable Grade-A Cashmere. Hand wash cold, lay flat to dry on towel.",
    shippingInfo: "Complimentary Zelevation dust bag and cedar moth repellent balls included.",
    isFeatured: true,
  },
  {
    id: "prod-5",
    name: "Architectural Leather Totebag",
    slug: "architectural-leather-totebag",
    subtitle: "Hand-Burnished Italian Calfskin",
    price: 11500,
    regularPrice: 14500,
    onSale: false,
    saleBadge: "ICONIC",
    description: "Sculptural geometric structured tote crafted by master leather artisans in Florence. Accommodates a 15-inch laptop, includes an internal zippered pouch, magnetic snap closure, and brushed palladium hardware.",
    shortDescription: "Full-grain Italian calfskin with geometric sculptural silhouette.",
    category: {
      name: "Accessories",
      slug: "accessories",
    },
    images: [
      {
        id: "img-5-1",
        sourceUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1000&q=85",
        altText: "Leather Tote bag editorial shot",
      },
      {
        id: "img-5-2",
        sourceUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&q=85",
        altText: "Interior compartments and handles",
      },
    ],
    colorOptions: [
      { name: "Saddle Tan", hex: "#8d5524" },
      { name: "Matte Black", hex: "#1a1a1a" },
      { name: "Burgundy Wine", hex: "#581845" },
    ],
    sku: "ZEL-BAG-003",
    stockQuantity: 8,
    inStock: true,
    rating: 4.9,
    reviewCount: 31,
    fabricCare: "Full-grain vegetable-tanned calfskin. Protect from heavy rain. Polish with leather balm.",
    shippingInfo: "Delivered in reinforced luxury hard box with archival dust bag.",
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: "prod-6",
    name: "Relaxed Boxy Cotton Tee (280 GSM)",
    slug: "relaxed-boxy-cotton-tee",
    subtitle: "Heavyweight Combed Organic Jersey",
    price: 1890,
    regularPrice: 2490,
    onSale: true,
    saleBadge: "ESSENTIAL",
    description: "The definitive luxury streetwear tee. Cut from 280 GSM organic combed long-staple cotton with a ribbed collar that never loses shape. Drop-shoulder cut with clean blind-stitched cuffs.",
    shortDescription: "280 GSM heavy organic cotton with zero-shrink pre-wash.",
    category: {
      name: "Men",
      slug: "men",
    },
    images: [
      {
        id: "img-6-1",
        sourceUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&q=85",
        altText: "Model wearing Heavyweight Boxy Tee",
      },
      {
        id: "img-6-2",
        sourceUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1000&q=85",
        altText: "Collar and fabric density view",
      },
    ],
    colorOptions: [
      { name: "Vintage Chalk", hex: "#f0ede6" },
      { name: "Pitch Black", hex: "#121212" },
      { name: "Washed Slate", hex: "#475569" },
    ],
    sizeOptions: ["S", "M", "L", "XL", "XXL"],
    sku: "ZEL-TEE-008",
    stockQuantity: 28,
    inStock: true,
    rating: 4.7,
    reviewCount: 64,
    fabricCare: "100% Certified Organic Cotton. Machine wash cold inside out. Hang dry.",
    shippingInfo: "Standard dispatch within 24h. Free returns within 7 days.",
    isFeatured: false,
    isNewArrival: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-8092",
    orderNumber: "ZEL-2026-8092",
    date: "September 12, 2026",
    status: "Delivered",
    total: 13480,
    shippingAddress: {
      fullName: "Aryan Sharma",
      addressLine: "Flat 402, Signature Heights, 100 Feet Road, Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560038",
      phone: "+91 98765 43210",
    },
    items: [
      {
        id: "item-1",
        name: "Sculpted Hourglass Wool Blazer",
        quantity: 1,
        price: 8490,
        image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&q=80",
        selectedSize: "M",
        selectedColor: "Obsidian Noir",
      },
      {
        id: "item-2",
        name: "Oversized Raw Silk Camp Shirt",
        quantity: 1,
        price: 4990,
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80",
        selectedSize: "L",
        selectedColor: "Raw Ecru",
      },
    ],
  },
  {
    id: "ord-8051",
    orderNumber: "ZEL-2026-8051",
    date: "August 28, 2026",
    status: "Delivered",
    total: 1890,
    shippingAddress: {
      fullName: "Aryan Sharma",
      addressLine: "Flat 402, Signature Heights, 100 Feet Road, Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560038",
      phone: "+91 98765 43210",
    },
    items: [
      {
        id: "item-3",
        name: "Relaxed Boxy Cotton Tee (280 GSM)",
        quantity: 1,
        price: 1890,
        image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400&q=80",
        selectedSize: "XL",
        selectedColor: "Vintage Chalk",
      },
    ],
  },
];
